name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '10', '8' ]
    name: Node ${{ matrix.node }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: install dependencies
      run: npm install
    - name: eslint check
      run: npm test

  build_latest:
    name: Node latest
    runs-on: ubuntu-latest
    container: node:current
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: npm install
    - name: eslint check
      run: npm test